name: retrace
version: 1.2.0
description: Regenerates minified stacktraces.
author: Björn Melinder <bjorn.melinder@gmail.com>
homepage: https://github.com/bjornm/retrace
dependencies:
  args: any
  source_maps: any
dev_dependencies:
  test: any

executables:
  retrace:

environment:
  sdk: '>=2.0.0-dev <3.0.0'
